modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "${issue_url}"

[[mods]]
modId = "${project_id}"
version = "${version}"
displayName = "${project_name}"
credits = "${authors}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${project_description}'''

[[mixins]]
config = "${project_id}.mixins.json"

# Forge Dependency
[[dependencies.${ project_id }]]
modId = "forge"
mandatory = false
type = "optional"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# NeoForge Dependency
[[dependencies.${ project_id }]]
modId = "neoforge"
mandatory = false
type = "optional"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${ project_id }]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# TaterLib
[[dependencies.${ project_id }]]
modId = "taterlib"
mandatory = false
type = "optional"
versionRange = "[${taterlib_version},)"
ordering = "NONE"
side = "SERVER"
