name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: 'dev.neuralnexus.testbed.platforms.BukkitLoaderPlugin'
depend: [ ]
depends: [ ]
softdepend: [ TaterLib ]
softdepends: [ TaterLib ]
folia-supported: true
